curl -X GET \
  'http://localhost:1026/version'


# HTTP/1.1 200 OK
# Connection: close
# Content-Length: 735
# Content-Type: application/json
# Fiware-Correlator: 92818f0c-9710-11ed-94da-0242ac120103
# Date: Wed, 18 Jan 2023 09:14:55 GMT

# {
#   "orion": {
#     "version": "3.7.0-next",
#     "uptime": "0 d, 0 h, 8 m, 22 s",
#     "git_hash": "c92ba18320ba692d72a8333dc86fa62bb1cd7ec8",
#     "compile_time": "Thu Dec 22 17:48:15 UTC 2022",
#     "compiled_by": "root",
#     "compiled_in": "70921c94dd4e",
#     "release_date": "Thu Dec 22 17:48:15 UTC 2022",
#     "machine": "x86_64",
#     "doc": "https://fiware-orion.rtfd.io/",
#     "libversions": {
#       "boost": "1_74",
#       "libcurl": "libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3",
#       "libmosquitto": "2.0.12",
#       "libmicrohttpd": "0.9.70",
#       "openssl": "1.1",
#       "rapidjson": "1.1.0",
#       "mongoc": "1.17.4",
#       "bson": "1.17.4"
#     }
#   }
# }
