curl -G -X GET \
    'http://localhost:1026/v2/entities?type=Store&options=keyValues'


# HTTP/1.1 200 OK
# Connection: close
# Content-Length: 529
# Content-Type: application/json
# Fiware-Correlator: 832ef9ae-9715-11ed-8ff1-0242ac120103
# Date: Wed, 18 Jan 2023 09:50:16 GMT

# [
#   {
#     "id": "urn:ngsi-ld:Store:001",
#     "type": "Store",
#     "address": {
#       "streetAddress": "Bornholmer Straße 65",
#       "addressRegion": "Berlin",
#       "addressLocality": "Prenzlauer Berg",
#       "postalCode": "10439"
#     },
#     "location": {
#       "type": "Point",
#       "coordinates": [
#         13.3986,
#         52.5547
#       ]
#     },
#     "name": "Bösebrücke Einkauf"
#   },
#   {
#     "id": "urn:ngsi-ld:Store:002",
#     "type": "Store",
#     "address": {
#       "streetAddress": "Friedrichstraße 44",
#       "addressRegion": "Berlin",
#       "addressLocality": "Kreuzberg",
#       "postalCode": "10969"
#     },
#     "location": {
#       "type": "Point",
#       "coordinates": [
#         13.3903,
#         52.5075
#       ]
#     },
#     "name": "Checkpoint Markt"
#   }
# ]
