curl -G -X GET \
    'http://localhost:1026/v2/entities?type=Store&q=address.addressLocality==Kreuzberg&options=keyValues'


# HTTP/1.1 200 OK
# Connection: close
# Content-Length: 259
# Content-Type: application/json
# Fiware-Correlator: 3870a5e2-9716-11ed-a0b1-0242ac120103
# Date: Wed, 18 Jan 2023 09:55:21 GMT

# [
#   {
#     "id": "urn:ngsi-ld:Store:002",
#     "type": "Store",
#     "address": {
#       "streetAddress": "Friedrichstraße 44",
#       "addressRegion": "Berlin",
#       "addressLocality": "Kreuzberg",
#       "postalCode": "10969"
#     },
#     "location": {
#       "type": "Point",
#       "coordinates": [
#         13.3903,
#         52.5075
#       ]
#     },
#     "name": "Checkpoint Markt"
#   }
# ]
