curl -G -X GET \
  'http://localhost:1026/v2/entities?q=refStore==urn:ngsi-ld:Store:001&type=Shelf&options=values&attrs=name'

# HTTP/1.1 200 OK
# Connection: close
# Content-Length: 49
# Content-Type: application/json
# Fiware-Correlator: d743915c-97d4-11ed-b37d-0242ac120103
# Date: Thu, 19 Jan 2023 08:39:51 GMT

# [
#   [
#     "Corner Unit"
#   ],
#   [
#     "Wall Unit 1"
#   ],
#   [
#     "Wall Unit 2"
#   ]
# ]
